In [1]:
import numpy as np
import matplotlib.pyplot as plt
from skimage.io import imread
import seaborn as sns
sns.set_style('white')
import matplotlib
import pandas as pd

%matplotlib qt5

In [2]:
df = pd.read_csv('C:/Users/Raket/OneDrive - Uppsala universitet/Desktop/Sommarjobb/Chromosome_project/data/3DForkPlots/chromosome/mCells_table.csv')

In [3]:
df = df.rename(columns={"channelName":"channelName"	,
                        "id":"id",
                        "trajImageCoord_1":"trajImX",
                        "trajImageCoord_2": "trajImY",
                        "trajImageCoord_3":"trajImZ",
                        "trajPhaseImageCoord_1": "trajPhaseX",
                        "trajPhaseImageCoord_2":"trajPhaseY",
                        "trajPhaseImageCoord_3":"trajPhaseZ",
                        "trajInternalCoord_1":"intX",
                        "trajInternalCoord_2":"intY",
                        "ampl":"phot"})

In [7]:
df['intY'] = df['intY']*df['width']*(65/2)

In [8]:
df['intX'] = df['intX']*df['length']*65

In [9]:
df

,channelName,id,trajImX,trajImY,trajImZ,trajPhaseX,trajPhaseY,trajPhaseZ,intX,intY,...,phot,bg,cellDetectionFrames,firstFrame,numberOfFrame,fluoTimes,blobLabels,prob,width,length
0,venus,3,398.652133,113.843660,-51.791374,398.652133,113.843660,-51.791374,1015.639193,-193.251007,...,1962.277100,NaN,1,1,1,NaN,1,1.022548,8.062258,30.223211
1,venus,4,407.877764,114.158797,-384.909912,407.877764,114.158797,-384.909912,1613.662890,-140.120745,...,2193.135010,NaN,1,1,1,NaN,1,1.049236,8.062258,30.223211
2,venus,5,426.373167,115.357204,-463.488953,426.373167,115.357204,-463.488953,708.512599,-250.665706,...,2509.477783,NaN,1,1,1,NaN,2,1.023518,9.055385,39.477363
3,venus,1,469.087981,113.394539,-55.469112,469.087981,113.394539,-55.469112,625.406625,121.843419,...,1682.198120,NaN,1,1,1,NaN,3,0.993432,9.055385,39.019393
4,venus,2,497.705228,113.147942,-470.246307,497.705228,113.147942,-470.246307,2488.292800,74.877757,...,1901.735962,NaN,1,1,1,NaN,3,0.934433,9.055385,39.019393
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13333,venus,469,902.386118,1030.097716,-371.615723,902.386118,1030.097716,-371.615723,1042.025391,-184.786835,...,2507.268311,NaN,30,1,1,NaN,323,1.044291,10.049876,28.043426
13334,venus,468,927.091587,1022.967548,-340.024506,927.091587,1022.967548,-340.024506,634.331517,319.771758,...,2512.099609,NaN,30,1,1,NaN,324,1.041701,11.045361,28.058834
13335,venus,470,930.613341,1031.254327,-341.877441,930.613341,1031.254327,-341.877441,841.628584,-227.821665,...,2222.165283,NaN,30,1,1,NaN,324,0.874172,11.045361,28.058834
13336,venus,472,1025.091587,1034.570192,-430.256714,1025.091587,1034.570192,-430.256714,623.694323,-99.426957,...,2229.739746,NaN,30,1,1,NaN,327,0.866134,9.055385,31.014247
13337,venus,471,1104.201322,1033.169591,402.539032,1104.201322,1033.169591,402.539032,639.359649,166.100424,...,2006.002686,NaN,30,1,1,NaN,328,0.806701,8.062258,48.143517

In [18]:
sns.scatterplot(data=df, x="intY", y="trajPhaseZ")

In [24]:
def generate_cat_columns(df_matches, n_bins, z_bounds = [-500, 500], phot_bounds = [700, 3000], y_bounds = [-400, 400], x_bounds = [-1000, 1000]):

    z_bins = np.linspace(z_bounds[0], z_bounds[1], n_bins)
    phot_bins = np.linspace(phot_bounds[0],phot_bounds[1], n_bins)
    prob_bins = np.linspace(0.1,1.3, n_bins)
    y_bins = np.linspace(y_bounds[0], y_bounds[1], n_bins)
    x_bins = np.linspace(x_bounds[0], x_bounds[1], n_bins)

    df_matches['z_cat'] = None
    df_matches['phot_cat'] = None
    df_matches['y_cat'] = None
    df_matches['x_cat'] = None

    df_matches['prob_cat'] = None


    for i in range(len(z_bins)-1):
        df_matches.loc[(df_matches['trajPhaseZ'] >= z_bins[i]) & (df_matches['trajPhaseZ'] <= z_bins[i+1]),'z_cat'] = z_bins[i]
        df_matches.loc[(df_matches['phot'] >= phot_bins[i]) & (df_matches['phot'] <= phot_bins[i+1]),'phot_cat'] = phot_bins[i]
        df_matches.loc[(df_matches['intY'] >= y_bins[i]) & (df_matches['intY'] <= y_bins[i+1]),'y_cat'] = y_bins[i]
        df_matches.loc[(df_matches['intX'] >= x_bins[i]) & (df_matches['intX'] <= x_bins[i+1]),'x_cat'] = x_bins[i]


        df_matches.loc[(df_matches['prob'] >= prob_bins[i]) & (df_matches['prob'] <= prob_bins[i+1]),'prob_cat'] = prob_bins[i]
    
    return df_matches, z_bins, phot_bins, y_bins, x_bins

In [27]:
labels_dict = {'z_cat':'Z (nm)', 'phot_cat': 'Photon count','GT_z_cat':'GT Z (nm)', 'GT_phot_cat': 'GT Photon count', 'z_error': 'z error (nm)', 'prob_cat':'Predicted probability', \
    'phot_error': 'photon count error', 'abs_z_error': 'absolute Z-error (nm)', 'abs_phot_error': 'absolute Photon count error', \
        'GT_z': 'ground truth Z (nm)', 'GT_phot': 'ground truth photon count', 'pred_z': 'predicted Z (nm)', 'pred_phot': 'predicted photon count'}

def plot_heatmap_mean(df, x_col, y_col, val_col, precision=0, extra_title='', count=False, x_bins=False, y_bins=False):



    if count:
        means = df.groupby([x_col, y_col]).count()[val_col].unstack(fill_value=0)
    else:
        means = df.groupby([x_col, y_col]).mean()[val_col].unstack(fill_value=0)

    zero_df = pd.DataFrame(index=x_bins, columns=y_bins)
    zero_df.fillna(0, inplace=True)
    zero_df.update(means)

    means = zero_df

    means = means.stack()
    means = means.sort_index()
    
    means_np = means.to_numpy()# Maybe add more bins and make sure axis are correct
    side_length = int(np.sqrt(means_np.shape[0]))
    
    fig, ax = plt.subplots()
    ar = np.array(means.index).reshape((side_length,side_length))
    x_axis_vals = np.array([val[0] for val in ar[:,0]])
    step = x_axis_vals[1] - x_axis_vals[0]
    x_axis_vals = (x_axis_vals + step//2).astype(int)


    y_axis_vals = np.array([val[1] for val in ar[0,::-1]])
    step = y_axis_vals[1] - y_axis_vals[0]
    y_axis_vals = (y_axis_vals - step//2).astype(int)

    data = np.flip(means_np.reshape((side_length,side_length)).T, axis=0)
    sns.heatmap(data, xticklabels=x_axis_vals, 
                yticklabels=y_axis_vals, annot=True, fmt=f".{precision}f", mask=(data==0))
    ax.set_xlabel(labels_dict[x_col])
    ax.set_ylabel(labels_dict[y_col])
    fig.suptitle(f"Mean {labels_dict[val_col]} for different photon counts and Z-positions \n {extra_title}")

    return data, fig, ax

In [25]:
df, z_bins, phot_bins, y_bins, x_bins = generate_cat_columns(df, 11)

In [26]:
df

,channelName,id,trajImX,trajImY,trajImZ,trajPhaseX,trajPhaseY,trajPhaseZ,intX,intY,...,fluoTimes,blobLabels,prob,width,length,z_cat,phot_cat,y_cat,x_cat,prob_cat
0,venus,3,398.652133,113.843660,-51.791374,398.652133,113.843660,-51.791374,1015.639193,-193.251007,...,NaN,1,1.022548,8.062258,30.223211,-100.0,1850.0,-240.0,None,0.94
1,venus,4,407.877764,114.158797,-384.909912,407.877764,114.158797,-384.909912,1613.662890,-140.120745,...,NaN,1,1.049236,8.062258,30.223211,-400.0,2080.0,-160.0,None,0.94
2,venus,5,426.373167,115.357204,-463.488953,426.373167,115.357204,-463.488953,708.512599,-250.665706,...,NaN,2,1.023518,9.055385,39.477363,-500.0,2310.0,-320.0,600.0,0.94
3,venus,1,469.087981,113.394539,-55.469112,469.087981,113.394539,-55.469112,625.406625,121.843419,...,NaN,3,0.993432,9.055385,39.019393,-100.0,1620.0,80.0,600.0,0.94
4,venus,2,497.705228,113.147942,-470.246307,497.705228,113.147942,-470.246307,2488.292800,74.877757,...,NaN,3,0.934433,9.055385,39.019393,-500.0,1850.0,0.0,None,0.82
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13333,venus,469,902.386118,1030.097716,-371.615723,902.386118,1030.097716,-371.615723,1042.025391,-184.786835,...,NaN,323,1.044291,10.049876,28.043426,-400.0,2310.0,-240.0,None,0.94
13334,venus,468,927.091587,1022.967548,-340.024506,927.091587,1022.967548,-340.024506,634.331517,319.771758,...,NaN,324,1.041701,11.045361,28.058834,-400.0,2310.0,240.0,600.0,0.94
13335,venus,470,930.613341,1031.254327,-341.877441,930.613341,1031.254327,-341.877441,841.628584,-227.821665,...,NaN,324,0.874172,11.045361,28.058834,-400.0,2080.0,-240.0,800.0,0.82
13336,venus,472,1025.091587,1034.570192,-430.256714,1025.091587,1034.570192,-430.256714,623.694323,-99.426957,...,NaN,327,0.866134,9.055385,31.014247,-500.0,2080.0,-160.0,600.0,0.82
13337,venus,471,1104.201322,1033.169591,402.539032,1104.201322,1033.169591,402.539032,639.359649,166.100424,...,NaN,328,0.806701,8.062258,48.143517,400.0,1850.0,160.0,600.0,0.7

In [51]:
# Plot heatmap

labels_dict['y_cat'] = 'Internal y'

p = 0.8
p_high = 3
shifted = False

max_phot = 1000
data_df = df[df['phot'] < max_phot].copy() 

data, fig, ax = plot_heatmap_mean(df=data_df, x_col='y_cat', y_col='z_cat', val_col='prob', precision = 0, count = True,extra_title='Shifted' if shifted else 'Not shifted',x_bins=y_bins, y_bins=z_bins);
fig.suptitle(f'Counts z/internal y, phot < {max_phot}', fontsize=16)

Text(0.5, 0.98, 'Counts z/internal y, phot < 1000')

In [41]:
df['phot'].hist()

In [54]:
fig, ax = plt.subplots()
y = list(data.sum(0))
step = y_bins[1] - y_bins[0]
x_axis_vals = (y_bins + step//2).astype(int)

plt.plot(x_axis_vals,y)
fig.suptitle(f'{"Shifted" if shifted else "Not Shifted"}, {p}< p < {p_high}')

Text(0.5, 0.98, 'Not Shifted, 0.8< p < 3')